//! Generates the encrypted-PDF test corpus (RC4/AES x user/owner password)
//! consumed by `pdf-manip` integration tests (Batch 4, T-025/T-026) and any
//! shell-level password-prompt testing (Batch 8+). See `spec.md` "Open
//! Password-Protected PDF" and `design.md`'s pdfium/lopdf security-handler
//! notes.
//!
//! Each corpus fixture is encrypted with a distinct, non-empty user password
//! AND a distinct, non-empty owner password, so a single file can exercise
//! both the "correct user password" and "correct owner password" open
//! scenarios from the spec.

use std::collections::BTreeMap;
use std::io;
use std::path::{Path, PathBuf};
use std::sync::Arc;

use lopdf::content::{Content, Operation};
use lopdf::encryption::crypt_filters::{Aes128CryptFilter, CryptFilter};
use lopdf::xref::XrefType;
use lopdf::{
    dictionary, Document, EncryptionState, EncryptionVersion, Object, Permissions, Stream,
};

pub mod large;
pub mod signed;

/// Encryption algorithm used for a corpus fixture.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Algorithm {
    /// RC4, 128-bit key (security handler /V 2, revision 3).
    Rc4_128,
    /// AES-128 (security handler /V 4, revision 4, crypt filter AESV2).
    Aes128,
}

/// Describes one fixture in the corpus: its output file name, the
/// encryption algorithm, and the distinct user/owner passwords used to
/// protect it.
#[derive(Debug, Clone, Copy)]
pub struct FixtureSpec {
    pub file_name: &'static str,
    pub algorithm: Algorithm,
    pub user_password: &'static str,
    pub owner_password: &'static str,
}

/// The full encrypted-PDF corpus generated by this tool: one RC4-128 fixture
/// and one AES-128 fixture, each with distinct user/owner passwords.
pub const CORPUS: &[FixtureSpec] = &[
    FixtureSpec {
        file_name: "rc4_128_user_and_owner.pdf",
        algorithm: Algorithm::Rc4_128,
        user_password: "user-rc4-pass",
        owner_password: "owner-rc4-pass",
    },
    FixtureSpec {
        file_name: "aes_128_user_and_owner.pdf",
        algorithm: Algorithm::Aes128,
        user_password: "user-aes-pass",
        owner_password: "owner-aes-pass",
    },
];

/// Builds a minimal, valid single-page PDF used as the base document for
/// every corpus fixture, before encryption is applied.
pub fn build_base_document(label: &str) -> Document {
    let mut doc = Document::with_version("1.5");
    let pages_id = doc.new_object_id();

    let font_id = doc.add_object(dictionary! {
        "Type" => "Font",
        "Subtype" => "Type1",
        "BaseFont" => "Helvetica",
    });
    let resources_id = doc.add_object(dictionary! {
        "Font" => dictionary! {
            "F1" => font_id,
        },
    });

    let content = Content {
        operations: vec![
            Operation::new("BT", vec![]),
            Operation::new("Tf", vec!["F1".into(), 24.into()]),
            Operation::new("Td", vec![100.into(), 700.into()]),
            Operation::new("Tj", vec![Object::string_literal(label)]),
            Operation::new("ET", vec![]),
        ],
    };
    let content_id = doc.add_object(Stream::new(
        dictionary! {},
        content.encode().expect("encode fixture content stream"),
    ));

    let page_id = doc.add_object(dictionary! {
        "Type" => "Page",
        "Parent" => pages_id,
        "Contents" => content_id,
        "Resources" => resources_id,
        "MediaBox" => vec![0.into(), 0.into(), 612.into(), 792.into()],
    });

    let pages = dictionary! {
        "Type" => "Pages",
        "Kids" => vec![page_id.into()],
        "Count" => 1,
    };
    doc.objects.insert(pages_id, Object::Dictionary(pages));

    let catalog_id = doc.add_object(dictionary! {
        "Type" => "Catalog",
        "Pages" => pages_id,
    });
    doc.trailer.set("Root", catalog_id);

    // The standard security handler's key-derivation algorithm requires the
    // first element of the trailer's /ID array (PDF 32000-1:2008 §7.6.3.3);
    // without it, `EncryptionState::encode`/`decrypt` fail with
    // `DecryptionError::MissingFileID`. A fixture-scoped, non-random value is
    // fine here — determinism is not a concern for test fixtures (unlike the
    // production `pdf-save` writer's injectable ID generator, Batch 6 T-036).
    let file_id = Object::string_literal(format!("{label}-fixture-id"));
    doc.trailer.set("ID", vec![file_id.clone(), file_id]);

    doc
}

/// Builds a small, unencrypted, plain-text multi-page PDF — used by
/// `pdf-render`'s actor/scheduling integration tests (Batch 3, T-020), which
/// need several *real* pages to request renders of, but not the encryption
/// machinery of [`build_base_document`]/[`CORPUS`] nor the raster-heavy
/// perf fixture in [`large`].
pub fn build_multi_page_document(num_pages: u32, label_prefix: &str) -> Document {
    let mut doc = Document::with_version("1.5");
    doc.reference_table.cross_reference_type = XrefType::CrossReferenceTable;

    let pages_id = doc.new_object_id();
    let font_id = doc.add_object(dictionary! {
        "Type" => "Font",
        "Subtype" => "Type1",
        "BaseFont" => "Helvetica",
    });
    let resources_id = doc.add_object(dictionary! {
        "Font" => dictionary! { "F1" => font_id },
    });

    let mut kids = Vec::with_capacity(num_pages as usize);
    for page_num in 0..num_pages {
        let label = format!("{label_prefix} page {page_num}");
        let content = Content {
            operations: vec![
                Operation::new("BT", vec![]),
                Operation::new("Tf", vec!["F1".into(), 24.into()]),
                Operation::new("Td", vec![100.into(), 700.into()]),
                Operation::new("Tj", vec![Object::string_literal(label)]),
                Operation::new("ET", vec![]),
            ],
        };
        let content_id = doc.add_object(Stream::new(
            dictionary! {},
            content.encode().expect("encode fixture content stream"),
        ));

        let page_id = doc.add_object(dictionary! {
            "Type" => "Page",
            "Parent" => pages_id,
            "Contents" => content_id,
            "Resources" => resources_id,
            "MediaBox" => vec![0.into(), 0.into(), 612.into(), 792.into()],
        });
        kids.push(page_id.into());
    }

    let pages = dictionary! {
        "Type" => "Pages",
        "Kids" => kids,
        "Count" => i64::from(num_pages),
    };
    doc.objects.insert(pages_id, Object::Dictionary(pages));

    let catalog_id = doc.add_object(dictionary! {
        "Type" => "Catalog",
        "Pages" => pages_id,
    });
    doc.trailer.set("Root", catalog_id);

    doc
}

/// Builds a small, unencrypted, single-page PDF whose page carries several
/// text lines at descending vertical positions — used to prove how pdfium's
/// text extraction separates visual lines (Batch 3 text-run work). Each label
/// in `lines` is drawn in its own text object at a distinct baseline.
pub fn build_multi_line_page_document(lines: &[&str]) -> Document {
    let mut doc = Document::with_version("1.5");
    doc.reference_table.cross_reference_type = XrefType::CrossReferenceTable;

    let pages_id = doc.new_object_id();
    let font_id = doc.add_object(dictionary! {
        "Type" => "Font",
        "Subtype" => "Type1",
        "BaseFont" => "Helvetica",
    });
    let resources_id = doc.add_object(dictionary! {
        "Font" => dictionary! { "F1" => font_id },
    });

    let mut operations = Vec::new();
    let mut baseline = 700;
    for line in lines {
        operations.push(Operation::new("BT", vec![]));
        operations.push(Operation::new("Tf", vec!["F1".into(), 24.into()]));
        operations.push(Operation::new("Td", vec![100.into(), baseline.into()]));
        operations.push(Operation::new("Tj", vec![Object::string_literal(*line)]));
        operations.push(Operation::new("ET", vec![]));
        baseline -= 40;
    }

    let content_id = doc.add_object(Stream::new(
        dictionary! {},
        Content { operations }
            .encode()
            .expect("encode fixture content stream"),
    ));

    let page_id = doc.add_object(dictionary! {
        "Type" => "Page",
        "Parent" => pages_id,
        "Contents" => content_id,
        "Resources" => resources_id,
        "MediaBox" => vec![0.into(), 0.into(), 612.into(), 792.into()],
    });

    let pages = dictionary! {
        "Type" => "Pages",
        "Kids" => vec![page_id.into()],
        "Count" => 1,
    };
    doc.objects.insert(pages_id, Object::Dictionary(pages));

    let catalog_id = doc.add_object(dictionary! {
        "Type" => "Catalog",
        "Pages" => pages_id,
    });
    doc.trailer.set("Root", catalog_id);

    doc
}

/// Encrypts `doc` in place according to `spec`'s algorithm and passwords.
pub fn encrypt_with_spec(doc: &mut Document, spec: &FixtureSpec) -> lopdf::Result<()> {
    let permissions = Permissions::PRINTABLE | Permissions::COPYABLE;

    let requested_version = match spec.algorithm {
        Algorithm::Rc4_128 => EncryptionVersion::V2 {
            document: doc,
            owner_password: spec.owner_password,
            user_password: spec.user_password,
            key_length: 128,
            permissions,
        },
        Algorithm::Aes128 => {
            let crypt_filter: Arc<dyn CryptFilter> = Arc::new(Aes128CryptFilter);
            EncryptionVersion::V4 {
                document: doc,
                encrypt_metadata: true,
                crypt_filters: BTreeMap::from([(b"StdCF".to_vec(), crypt_filter)]),
                stream_filter: b"StdCF".to_vec(),
                string_filter: b"StdCF".to_vec(),
                owner_password: spec.owner_password,
                user_password: spec.user_password,
                permissions,
            }
        }
    };

    let state = EncryptionState::try_from(requested_version)?;
    doc.encrypt(&state)?;
    Ok(())
}

/// Generates the full corpus into `out_dir`, creating the directory if
/// needed. Returns the paths of all written fixture files, in `CORPUS` order.
pub fn generate_all(out_dir: &Path) -> io::Result<Vec<PathBuf>> {
    std::fs::create_dir_all(out_dir)?;

    let mut written = Vec::with_capacity(CORPUS.len());
    for spec in CORPUS {
        let mut doc = build_base_document(&format!("Fixture: {}", spec.file_name));

        // Force the traditional (classic xref table, no object streams) save
        // format: lopdf's decrypt path (`decrypt_raw`) only re-hydrates
        // objects already resident in `Document::objects` after load, and an
        // encrypted cross-reference-stream/object-stream file leaves the
        // compressed objects undecodable (ciphertext) at load time, before
        // decryption — so they're never populated for decrypt_raw to unpack.
        // `Document::new()` defaults every fresh document to
        // `XrefType::CrossReferenceStream` regardless of PDF version, so this
        // must be set explicitly; the classic table format has no such
        // chicken-and-egg problem.
        doc.reference_table.cross_reference_type = XrefType::CrossReferenceTable;

        encrypt_with_spec(&mut doc, spec).map_err(|e| io::Error::other(e.to_string()))?;

        let out_path = out_dir.join(spec.file_name);
        doc.save(&out_path)
            .map_err(|e| io::Error::other(e.to_string()))?;
        written.push(out_path);
    }

    Ok(written)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn corpus_covers_rc4_and_aes() {
        let algorithms: Vec<Algorithm> = CORPUS.iter().map(|s| s.algorithm).collect();
        assert!(algorithms.contains(&Algorithm::Rc4_128));
        assert!(algorithms.contains(&Algorithm::Aes128));
    }

    #[test]
    fn corpus_entries_have_distinct_nonempty_user_and_owner_passwords() {
        for spec in CORPUS {
            assert!(!spec.user_password.is_empty());
            assert!(!spec.owner_password.is_empty());
            assert_ne!(spec.user_password, spec.owner_password);
        }
    }

    #[test]
    fn build_base_document_has_one_page() {
        let doc = build_base_document("test");
        assert_eq!(doc.get_pages().len(), 1);
    }
}
