//! T-191's measurement, kept as a test so the numbers in the ficha can be
//! re-derived rather than believed.
//!
//! `docs/batch-compress.md` fact 4 is written as a question, not a claim:
//! *today's save path rewrites a document that arrived with object streams as
//! loose objects plus a classic cross-reference table, and that may inflate
//! it — measure, do not assume.* This file is the measurement. It walks the
//! repository's real PDF corpus and, for each file, reports three sizes:
//!
//! 1. what the user handed us,
//! 2. what today's `pdf-save` full rewrite produces (`load_mem` + `save_to`,
//!    `strategy.rs:451`),
//! 3. what [`pdf_compress::compress`] produces.
//!
//! Run the table yourself with:
//!
//! ```text
//! cargo test -p pdf-compress --test corpus -- --nocapture measure
//! ```
//!
//! The rest of the file is the part that runs in CI: a guardian that no real
//! document in the corpus grows under any preset, that every page survives,
//! and that the protected files come back untouched. T-197 widens this corpus
//! (a scan, a pure-vector file, one with real transparency); T-191 measures
//! what the repository already has.

use std::path::{Path, PathBuf};

use pdf_compress::{compress, CompressPreset, Outcome, Refusal};

/// One corpus entry: where it lives, and what it is there to represent.
struct Fixture {
    path: &'static str,
    what: &'static str,
    /// Generated by `gen-fixtures` rather than committed, so a clean checkout
    /// that has not run the generator simply has fewer rows.
    generated: bool,
    /// Encrypted or signed: this crate hands it back untouched, so it is a
    /// row about a refusal rather than about a saving.
    protected: bool,
}

const CORPUS: &[Fixture] = &[
    Fixture {
        path: "assets/sample/vitela-sample.pdf",
        what: "the app's own sample document",
        generated: false,
        protected: false,
    },
    Fixture {
        path: "tests/fixtures/content-edit/reportlab_embedded_subset.pdf",
        what: "real producer output, embedded subset fonts",
        generated: false,
        protected: false,
    },
    Fixture {
        path: "tests/fixtures/signed/rsa2048_sha256.pdf",
        what: "signed (RSA-2048/SHA-256)",
        generated: false,
        protected: true,
    },
    Fixture {
        path: "tests/fixtures/signed/two_signatures_rsa2048_sha256.pdf",
        what: "signed twice",
        generated: false,
        protected: true,
    },
    Fixture {
        path: "tests/fixtures/encrypted/rc4_128_user_and_owner.pdf",
        what: "encrypted (RC4-128)",
        generated: false,
        protected: true,
    },
    Fixture {
        path: "tests/fixtures/encrypted/aes_128_user_and_owner.pdf",
        what: "encrypted (AES-128)",
        generated: false,
        protected: true,
    },
    Fixture {
        path: "tests/fixtures/large/edit_reopen_10pg.pdf",
        what: "10 pages",
        generated: true,
        protected: false,
    },
    Fixture {
        path: "tests/fixtures/large/edit_reopen_50pg.pdf",
        what: "50 pages",
        generated: true,
        protected: false,
    },
    Fixture {
        path: "tests/fixtures/large/perf_200pg.pdf",
        what: "200 pages, raster-heavy",
        generated: true,
        protected: false,
    },
];

fn repository_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("..")
        .join("..")
        .canonicalize()
        .expect("the crate sits two directories below the repository root")
}

/// Loads a corpus entry, or `None` when it is a generated fixture that has
/// not been generated in this checkout.
fn read(fixture: &Fixture) -> Option<Vec<u8>> {
    let path = repository_root().join(fixture.path);
    match std::fs::read(&path) {
        Ok(bytes) => Some(bytes),
        Err(_) if fixture.generated => None,
        Err(err) => panic!("committed fixture {} is missing: {err}", fixture.path),
    }
}

/// What today's `pdf-save` full rewrite does to these bytes: load them, write
/// them straight back out with `save_to`. Fact 2's "most expensive path in
/// lopdf" — every object serialised individually under a classic xref table.
///
/// `None` when the document is encrypted, because this path does not merely
/// inflate one: `load_mem` on an encrypted file returns a handle holding
/// nothing but its `/Encrypt` dictionary, so re-serialising it writes out an
/// *empty* PDF. Reporting that as a size would put a spectacular saving in
/// the table for a file that was destroyed.
fn todays_full_rewrite(input: &[u8]) -> Option<usize> {
    let mut document = lopdf::Document::load_mem(input).ok()?;
    if document.is_encrypted() {
        return None;
    }

    let mut bytes = Vec::new();
    document.save_to(&mut bytes).ok()?;
    Some(bytes.len())
}

fn page_count(bytes: &[u8]) -> Option<usize> {
    lopdf::Document::load_mem(bytes)
        .ok()
        .map(|document| document.get_pages().len())
}

fn percent(before: usize, after: usize) -> f64 {
    if before == 0 {
        return 0.0;
    }
    (after as f64 - before as f64) / before as f64 * 100.0
}

/// Fact 4's actual question, which no fixture in this repository can answer:
/// *what does today's save path do to a document that arrived **with** object
/// streams?* Every committed fixture was written with a classic
/// cross-reference table, so this builds the missing case — takes one of them
/// and re-writes it the modern way first — and measures the round trip
/// through `save_to`.
///
/// Returns `(packed input size, size after today's full rewrite)`.
fn modern_document_through_todays_rewrite(input: &[u8]) -> Option<(usize, usize)> {
    let mut document = lopdf::Document::load_mem(input).ok()?;
    if document.is_encrypted() {
        return None;
    }

    let mut packed = Vec::new();
    document
        .save_with_options(
            &mut packed,
            lopdf::SaveOptions {
                use_object_streams: true,
                use_xref_streams: true,
                ..lopdf::SaveOptions::default()
            },
        )
        .ok()?;

    let rewritten = todays_full_rewrite(&packed)?;
    Some((packed.len(), rewritten))
}

/// Fact 4, measured. Prints the table that goes into `docs/batch-compress.md`.
#[test]
fn measure_todays_rewrite_against_the_structural_pass() {
    println!(
        "\n{:<52} {:>10} {:>14} {:>14} {:>9}",
        "fixture", "original", "save_to today", "compress()", "vs orig"
    );

    for fixture in CORPUS {
        let Some(input) = read(fixture) else {
            println!("{:<52} {:>10}", fixture.path, "(not generated)");
            continue;
        };

        let rewritten = todays_full_rewrite(&input);
        let compressed = compress(&input, CompressPreset::Lossless)
            .unwrap_or_else(|err| panic!("{} could not be compressed: {err}", fixture.path));

        let rewritten_cell = match rewritten {
            Some(size) => format!("{size} ({:+.1}%)", percent(input.len(), size)),
            None => "destroys it".to_string(),
        };

        println!(
            "{:<52} {:>10} {:>14} {:>14} {:>8.1}%",
            fixture.path,
            input.len(),
            rewritten_cell,
            compressed.bytes().len(),
            percent(input.len(), compressed.bytes().len()),
        );
        println!(
            "{:<52} — {:?}, {} streams flated, {} objects dropped{}",
            format!("  ({})", fixture.what),
            compressed.report().outcome(),
            compressed.report().work().streams_recompressed,
            compressed.report().work().objects_dropped,
            if compressed.report().refusals().is_empty() {
                String::new()
            } else {
                format!(", refused: {:?}", compressed.report().refusals())
            }
        );
    }

    println!(
        "\nfact 4 — a document that arrived ALREADY packed, put through today's save_to:\n{:<52} {:>10} {:>14} {:>9}",
        "fixture (repacked first)", "packed", "save_to today", "delta"
    );
    for fixture in CORPUS {
        // Protected documents are excluded rather than shown: the packing
        // step this row starts from is itself what drops their signature, so
        // the "packed" figure would not describe the same document and the
        // delta would be theatre.
        if fixture.protected {
            continue;
        }
        let Some(input) = read(fixture) else {
            continue;
        };
        let Some((packed, rewritten)) = modern_document_through_todays_rewrite(&input) else {
            continue;
        };

        println!(
            "{:<52} {:>10} {:>14} {:>8.1}%",
            fixture.path,
            packed,
            rewritten,
            percent(packed, rewritten)
        );
    }
    println!();
}

/// Fact 4 as an assertion rather than a printout: today's full rewrite really
/// does inflate a document that arrived packed. This is the regression the
/// compression feature closes on its way past — not a claim in the ficha, a
/// test that fails if it ever stops being true.
#[test]
fn todays_full_rewrite_inflates_a_document_that_arrived_packed() {
    let input = read(&CORPUS[1]).expect("the content-edit fixture is committed");

    let (packed, rewritten) =
        modern_document_through_todays_rewrite(&input).expect("it is neither encrypted nor broken");

    assert!(
        rewritten > packed,
        "today's save_to turned a {packed}-byte packed document into {rewritten} bytes; \
         if this is no longer true, fact 4 in docs/batch-compress.md is stale"
    );
}

/// The guarantee, against files nobody in this repository wrote to be
/// compressible. T-197 owns the widened corpus; this is the same assertion on
/// the corpus that exists today.
#[test]
fn no_real_document_grows_under_any_preset() {
    for fixture in CORPUS {
        let Some(input) = read(fixture) else {
            continue;
        };

        for preset in CompressPreset::all() {
            let compressed = compress(&input, preset)
                .unwrap_or_else(|err| panic!("{} could not be compressed: {err}", fixture.path));

            assert!(
                compressed.bytes().len() <= input.len(),
                "{preset:?} grew {} from {} to {} bytes",
                fixture.path,
                input.len(),
                compressed.bytes().len()
            );
        }
    }
}

/// The failure the never-grow rule cannot see: a smaller file with less in
/// it. Every document that came back changed must still hold every page it
/// arrived with.
#[test]
fn no_real_document_loses_a_page() {
    for fixture in CORPUS {
        let Some(input) = read(fixture) else {
            continue;
        };
        let Some(before) = page_count(&input) else {
            continue;
        };

        let compressed = compress(&input, CompressPreset::Lossless).expect("compressible");

        assert_eq!(
            page_count(compressed.bytes()),
            Some(before),
            "{} came back with a different number of pages",
            fixture.path
        );
    }
}

/// The two traps, on the real protected files rather than built ones. A
/// document this crate cannot repack without taking something away must come
/// back byte for byte, with the refusal that explains why nothing happened.
///
/// The signed half is the one the measurement found: before the check landed,
/// `rsa2048_sha256.pdf` compressed to 92% smaller with its page intact,
/// because the 92% was the signature.
#[test]
fn a_protected_document_comes_back_exactly_as_it_arrived() {
    let cases = [
        ("/encrypted/", Refusal::EncryptedDocumentNotRewritable),
        ("/signed/", Refusal::SignaturesWouldBeInvalidated),
    ];

    for (kind, expected) in cases {
        let matching: Vec<&Fixture> = CORPUS
            .iter()
            .filter(|fixture| fixture.path.contains(kind))
            .collect();
        assert!(
            !matching.is_empty(),
            "the corpus must keep at least one {kind} document"
        );

        for fixture in matching {
            let input = read(fixture).expect("the protected fixtures are committed");

            for preset in CompressPreset::all() {
                let compressed = compress(&input, preset).expect("not an error");

                assert_eq!(
                    compressed.bytes(),
                    input.as_slice(),
                    "{} was rewritten; a protected document must be handed back untouched",
                    fixture.path
                );
                assert_eq!(compressed.report().outcome(), Outcome::NoGain);
                assert_eq!(
                    compressed.report().refusals(),
                    std::slice::from_ref(&expected),
                    "{} must say why it was left alone",
                    fixture.path
                );
            }
        }
    }
}

/// T-192's fixed point, on the real corpus rather than on a built fixture.
///
/// Compressing a document this crate already compressed must return the very
/// same bytes: [`Outcome::NoGain`], nothing dropped, nothing recompressed.
/// Before the prune landed it failed here for a reason no user could ever
/// have seen — the second pass produced a *larger* file, the never-grow
/// guarantee caught it and handed the original back, and the outcome read
/// `NoGain` either way. The guarantee was covering for a repack that leaked
/// one dead cross-reference object and two object ids per round trip.
#[test]
fn compressing_a_compressed_document_is_a_no_op_on_every_fixture() {
    for fixture in CORPUS {
        let Some(input) = read(fixture) else {
            continue;
        };

        let once = compress(&input, CompressPreset::Lossless)
            .unwrap_or_else(|err| panic!("{} could not be compressed: {err}", fixture.path))
            .into_bytes();
        let twice = compress(&once, CompressPreset::Lossless).expect("compressible");

        assert_eq!(
            twice.bytes(),
            once.as_slice(),
            "{} was not a fixed point: {} bytes became {}",
            fixture.path,
            once.len(),
            twice.bytes().len()
        );
        assert_eq!(twice.report().outcome(), Outcome::NoGain);
        assert_eq!(twice.report().work(), pdf_compress::Work::default());
    }
}
