//! The corpus: the repository's real PDFs, and how to read them.
//!
//! Shared by every integration test in this crate, because "which files are we
//! answerable to" is one list. A copy per test file is a corpus that drifts,
//! and a fixture added in one place and forgotten in another is exactly the
//! hole these tests exist to close.
//!
//! `tests/corpus.rs` holds the guardians that run in CI; `tests/measure.rs`
//! holds T-191's measurement, which prints a table rather than asserting;
//! `tests/render_unchanged.rs` rasterises and compares. All three read the
//! corpus from here.

#![allow(dead_code)]

use std::path::{Path, PathBuf};

/// One corpus entry: where it lives, and what it is there to represent.
pub struct Fixture {
    pub path: &'static str,
    pub what: &'static str,
    /// Generated by `gen-fixtures` rather than committed, so a clean checkout
    /// that has not run the generator simply has fewer rows.
    pub generated: bool,
    /// Encrypted or signed: this crate hands it back untouched, so it is a
    /// row about a refusal rather than about a saving.
    pub protected: bool,
}

pub const CORPUS: &[Fixture] = &[
    Fixture {
        path: "assets/sample/vitela-sample.pdf",
        what: "the app's own sample document",
        generated: false,
        protected: false,
    },
    Fixture {
        path: "tests/fixtures/content-edit/reportlab_embedded_subset.pdf",
        what: "real producer output, embedded subset fonts",
        generated: false,
        protected: false,
    },
    Fixture {
        path: "tests/fixtures/signed/rsa2048_sha256.pdf",
        what: "signed (RSA-2048/SHA-256)",
        generated: false,
        protected: true,
    },
    Fixture {
        path: "tests/fixtures/signed/two_signatures_rsa2048_sha256.pdf",
        what: "signed twice",
        generated: false,
        protected: true,
    },
    Fixture {
        path: "tests/fixtures/encrypted/rc4_128_user_and_owner.pdf",
        what: "encrypted (RC4-128)",
        generated: false,
        protected: true,
    },
    Fixture {
        path: "tests/fixtures/encrypted/aes_128_user_and_owner.pdf",
        what: "encrypted (AES-128)",
        generated: false,
        protected: true,
    },
    // T-197's rows: the cases the repository's own documents cannot make.
    // Committed rather than generated, because CI never runs `gen-fixtures`
    // and a guardian that skips in CI is not a guardian — see
    // `tests/fixtures/gen-fixtures/src/compress/mod.rs` for the trade.
    Fixture {
        path: "tests/fixtures/compress/scan_200dpi.pdf",
        what: "a scan: one lossy image at 200 effective dpi",
        generated: false,
        protected: false,
    },
    Fixture {
        path: "tests/fixtures/compress/reused_image_two_scales.pdf",
        what: "one image XObject painted large and small",
        generated: false,
        protected: false,
    },
    Fixture {
        path: "tests/fixtures/compress/transparency_smask.pdf",
        what: "real transparency: an image with a soft mask",
        generated: false,
        protected: false,
    },
    Fixture {
        path: "tests/fixtures/compress/vector_only.pdf",
        what: "pure vector: no image for the image stage to find",
        generated: false,
        protected: false,
    },
    Fixture {
        path: "tests/fixtures/compress/already_packed.pdf",
        what: "object streams, xref stream, every stream flated",
        generated: false,
        protected: false,
    },
    Fixture {
        path: "tests/fixtures/large/edit_reopen_10pg.pdf",
        what: "10 pages",
        generated: true,
        protected: false,
    },
    Fixture {
        path: "tests/fixtures/large/edit_reopen_50pg.pdf",
        what: "50 pages",
        generated: true,
        protected: false,
    },
    Fixture {
        path: "tests/fixtures/large/perf_200pg.pdf",
        what: "200 pages, raster-heavy",
        generated: true,
        protected: false,
    },
];

pub fn repository_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("..")
        .join("..")
        .canonicalize()
        .expect("the crate sits two directories below the repository root")
}

/// Loads a corpus entry, or `None` when it is a generated fixture that has
/// not been generated in this checkout.
pub fn read(fixture: &Fixture) -> Option<Vec<u8>> {
    let path = repository_root().join(fixture.path);
    match std::fs::read(&path) {
        Ok(bytes) => Some(bytes),
        Err(_) if fixture.generated => None,
        Err(err) => panic!("committed fixture {} is missing: {err}", fixture.path),
    }
}

/// The corpus entry whose path ends in `file_name`.
///
/// Panics rather than returning an `Option`: a test naming a fixture that is
/// not in the corpus is a test that would otherwise pass by looking at
/// nothing, which is the failure mode this whole harness exists to prevent.
pub fn fixture(file_name: &str) -> &'static Fixture {
    CORPUS
        .iter()
        .find(|fixture| fixture.path.ends_with(file_name))
        .unwrap_or_else(|| panic!("{file_name} is not in the corpus"))
}

/// How many pages `bytes` has, or `None` if it is not a readable document.
pub fn page_count(bytes: &[u8]) -> Option<usize> {
    lopdf::Document::load_mem(bytes)
        .ok()
        .map(|document| document.get_pages().len())
}

/// `after` as a signed percentage change from `before`.
pub fn percent(before: usize, after: usize) -> f64 {
    if before == 0 {
        return 0.0;
    }
    (after as f64 - before as f64) / before as f64 * 100.0
}
